spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userbook?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

jwt:
  secret: slkdfjh3ir1@REFiw
  expiration: 6000000